### PR TITLE
chore(housekeeping): rename module name

### LINKED ISSUE #121: chore(housekeeping): Rename Module Name of Golang

### PR DESCRIPTION
**Pull request by dustindemmerle**
## Description

This PR replaces the former module name (github.wdf.sap.corp/cc/heureka) with the current (github.com/cloudoperators/heureka). 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [X] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #121 
https://github.com/cloudoperators/heureka/issues/121

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [X] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by drochow — DISMISSED** [review]
LGTM! Good Job!

**Comment by MR2011** [comment]
Looks like you forgot: 
``` 
Error: auth.go:12:2: no required module provides package github.wdf.sap.corp/cc/heureka/internal/util; to add it:
	go get github.wdf.sap.corp/cc/heureka/internal/util
```

**Comment by drochow** [comment]
That probably came from a merge back.

**Comment by drochow** [comment]
@dustindemmerle, can you check the actual state and check again for anything that got merged back while merging? Thanks!

**Review by MR2011 — APPROVED** [review]

**Pull request merged**
