### PR TITLE
chore(rn): add resource name to additional entities

### PR DESCRIPTION
**Pull request by BlakePatterson**
## Description

This PR adds resource name to four entities to make identification easier. 

The Name field has been replaced with CCRN in the following entities:
- Service
- Component
- Support Group

And CCRN has been added to the following entity:
- Component Version

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Closes [#241](https://github.com/cloudoperators/heureka/issues/241)

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Updated all existing tests (db, app, e2e) to use the CCRN field in place of Name for the first three entities, and added an additional test and additional checks to existing tests for the new CCRN field in Component Version. All tests pass locally. 

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🤝 Documentation pages updated
- [x] 🙅 no documentation needed
- [ ] (if applicable) generated OpenAPI docs for CRD changes

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by MR2011** [comment]
1. Do we want to add the `CCRN` to `IssueRepository` as well?
2. The `ComponentVersion` has now the two fields `Version` and `CCRN`. Do we want to keep them both?

WDY @dorneanu @drochow

**Comment by drochow** [comment]
I think we should, for ComponentVersion, only keep the version. 

If we keep the CCRN on the component Version we could throw away the component because a specific version of an image would e.g. have the following CCRN: 

`ccrn: registry=ghcr.io, account=cloudoperators, repo=heureka-core, digest=sha256:<somshaValue>`

This would mean it would include the info that is currently within the component version:
"registry=ghcr.io, account=cloudoperators, repo=heureka-core"

As a result, you could not attach the same version to multiple components, e.g., the same image/version on a mirror.

- 

We could also decide to do so but that I'd argue we can remove the component from the schema.

**Comment by MR2011** [comment]
Let's remove CCRN from ComponentVersion then. @BlakePatterson @drochow

**Comment by BlakePatterson** [comment]
CCRN is now removed from ComponentVersion and the conflicts with main are resolved.

**Review by MR2011 — APPROVED** [review]

**Review by drochow — APPROVED** [review]

**Pull request merged**
